name: Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v5

    - name: Install .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Download Dalamud
      run: |
        Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
        Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev"

    - name: Build
      run: dotnet build JobRoulettePlugin/JobRoulettePlugin.csproj --configuration Release -p:Platform=x64

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: JobRoulettePlugin
        path: JobRoulettePlugin\bin\x64\Release\JobRoulettePlugin\*
        if-no-files-found: error
        retention-days: 7
